### PR TITLE
Automate Brew Releases

### PR DESCRIPTION
**Pull request by jordan-rash**
This should allow brew formulas to be updated in sync with the release cadence of the repositories

### CODE REVIEW

**Comment by jordan-rash** [comment]
Demo: https://github.com/jordan-rash/homebrew-wasmcloud/pull/1

**Comment by jordan-rash** [comment]
Example Action file:
```yaml
name: Brew Update
on:
  release:
    types: [released]

jobs:
  checkout_generate:
    name: "Checkout repo and generate new Ruby Gem"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: jordan-rash/homebrew-wasmcloud
          path: wcbrew
          token: #####
      - name: Generate new
        uses: jordan-rash/homebrew-wasmcloud@v0.1.0
        with:
          repo: wash
          releasetag: vTEST
          releasesha: 123TEST
      - name: Replace file
        run: |
          mv wash.rb.new ./wcbrew/Formula/wash.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: releasebump/vTEST
          title: "Automated PR - version bump"
          path: wcbrew
          token: #####

```

**Review by brooksmtownsend — APPROVED** [review]
This is awesome (looks like you need to fix the DCO)

**Review by autodidaddict — APPROVED** [review]
There's something hilarious and fun about using `Go` to update templates to produce `Ruby` files.

Since the wasmCloud binary is no longer distributed via brew, should we maybe remove/deprecate that?

**Comment by brooksmtownsend** [comment]
> There's something hilarious and fun about using Go to update templates to produce Ruby files.
Go to update Ruby files to distribute Rust binaries

> Since the wasmCloud binary is no longer distributed via brew, should we maybe remove/deprecate that?

That's a good idea, we should probably ensure it's all the way updated `v0.18.2`, but we can keep it just in case we decide to patch a vulnerability or something. Doubtful many people are still on the Rust host

**Comment by jordan-rash** [comment]
> Since the wasmCloud binary is no longer distributed via brew, should we maybe remove/deprecate that?

I can def pull out (or figure out how to deprecate) the wasmcloud piece.  That being said, is it always going to be that way?  I know that we have all the pieces in place to keep using brew (with the new otp release process) if it is desired....just have to change how it unpacks some things.

**Comment by autodidaddict** [comment]
From here on out, the wasmCloud host itself will be a tarball containing an Elixir distribution release, and will never again be a freestanding binary. If `brew` is also capable of deploying tarballs and making `{tarball}/bin` part of the user's path, then we can experiment with that. thoughts @brooksmtownsend ?

**Comment by brooksmtownsend** [comment]
That's very true, we could support installing via brew if we just fetch the release tarball for macos... That would probably be the best way forward.

**Comment by brooksmtownsend** [comment]
This is all tangental to this PR though, this all looks good and I think it's ready to merge, we can bring the other stuff in w/ another PR

**Comment by jordan-rash** [comment]
I agree @brooksmtownsend ......will set this up in `wash` only for now and I will play with the Elixir stuff....but it should def work with a little tinkering

**Pull request merged**
